plugin.plugin_configuration.search_api_solr_connector.hosted_solr:
  type: plugin.plugin_configuration.search_api_solr_connector.standard
  label: 'Hosted Solr connector settings'
  mapping:
    username:
      type: string
      label: 'Username for HTTP basic authentication'
    password:
      type: string
      label: 'Password for HTTP basic authentication'
