name: Run Tests

on:
    push:

    pull_request:

    schedule:
        - cron: '0 9 * * *' # run at 09:00 UTC

jobs:
    run-tests:
        runs-on: ubuntu-latest

        strategy:
            # As we run all combinations against the same remote core, run one after the other.
            max-parallel: 1
            matrix:
                drupal: ['9.5', '10.0']
                php: ['7.4', '8.1']
                exclude:
                  - drupal: '10.0'
                    php: '7.4'

        name: Drupal ${{ matrix.drupal }}, PHP ${{ matrix.php }}

        env:
          COMPOSER_MEMORY_LIMIT: -1

        steps:
            - name: Setup sqlite
              run: |
                sudo apt-get update
                sudo apt-get install sqlite3 libsqlite3-dev

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: dom, curl, libxml, mbstring, zip, pdo, sqlite, pdo_sqlite, bcmath, intl, gd, iconv, json, simplexml
                ini-values: memory_limit=256M,post_max_size=256M
                coverage: none

            - name: Checkout drupal
              uses: actions/checkout@v3
              with:
                repository: drupal/drupal
                ref: ${{ matrix.drupal }}.x
                path: drupal

            - name: Checkout hosted_solr
              uses: actions/checkout@v3
              with:
                path: hosted_solr
                fetch-depth: 0

            - name: Tag hosted_solr
              run: |
                cd hosted_solr
                git tag 1.1.99

            - name: Install dependencies
              run: |
                cd drupal
                composer --version
                composer config repositories.hosted_solr '{"type": "vcs", "url": "../hosted_solr"}'
                composer require solarium/solarium:"dev-master as 6.2.99" drupal/search_api_solr:4.x-dev drupal/hosted_solr:1.1.99 drupal/search_api_autocomplete:1.x-dev drupal/search_api_spellcheck:3.x-dev drupal/facets:3.0.x-dev drupal/devel drupal/search_api_location:1.x-dev drupal/geofield drush/drush monolog/monolog --ignore-platform-reqs --no-interaction
                composer run-script drupal-phpunit-upgrade

            #- name: Install search_api_location
            #  if: matrix.drupal != '9.0'
            #  run: |
            #    cd drupal
            #    composer require drupal/search_api_location

            - name: Run tests
              env:
                SOLR_INDEX_WAIT: 4
                SYMFONY_DEPRECATIONS_HELPER: disabled
                HOSTED_SOLR_HOST: ${{ secrets.HOSTED_SOLR_HOST }}
                HOSTED_SOLR_USER: ${{ secrets.HOSTED_SOLR_USER }}
                HOSTED_SOLR_PASSWORD: ${{ secrets.HOSTED_SOLR_PASSWORD }}
              run: |
                cp hosted_solr/tests/github.phpunit.xml drupal/core/phpunit.xml.dist
                cd drupal
                php -S localhost:8888 >& /dev/null &
                vendor/bin/drush si standard --db-url=sqlite://sites/default/files/db.sqlite --yes
                vendor/bin/drush en hosted_solr --yes
                vendor/bin/drush en search_api_spellcheck,search_api_autocomplete,facets,search_api_location --yes
                vendor/bin/phpunit -v -c core --group hosted_solr modules/contrib/hosted_solr
